apiVersion: apps/v1
kind: Deployment
metadata:
  name: meupod-deploy
  labels:
    app: meupod-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: meupod-deploy
  template:
    metadata:
      labels:
        app: meupod-deploy
    spec:
      containers:
      - name: meupod-deploy
        image: gabrielsoliva/gbrimg:v3
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: meupod-svc
spec:
  selector:
    app: meupod-deploy
  type: NodePort  
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
