apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-pod
  name: redis-pod
spec:
  containers:
  - image: redis
    name: redis-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


---

apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis-pod
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 80
      protocol: TCP
