apiVersion: v1 
kind: Pod 
metadata: 
 name: usuarios-pod 
 labels:
   app: usuarios 
spec: 
 volumes:
 - name: logs-volume
   emptyDir: {}
 containers:
 - name: logs-container
   image: busybox 
   volumeMounts:
   - name: logs-volume 
     mountPath: /tmp
   args:
    - sleep
    - 1d
 - name: apache
   image: httpd
   volumeMounts:
   - name: logs-volume
     mountPath: /var/logs/http2 
   envFrom: 
   -  configMapRef:
       name: usuarios-cm
   env:
    - name: USUARIO_PASSWORD 
      valueFrom:
        configMapKeyRef:
         name: usuarios-cm
         key: database_user 
        
